### PR TITLE
LOCUS-43 tycho 0.22; upversion to 1.3; fix missing TP resolution deps

### PR DESCRIPTION
**Pull request by nickboldt**
move up to use org.jboss.tools.tycho-plugins 0.22.1-SNAPSHOT and tycho 0.22.0; bump TP version to 1.3 (not 1.0); fix missing dependencies so we can resolve the TP, including sources

### CODE REVIEW

**Comment by nickboldt** [comment]
To build this PR, you need to run maven like this:

    maven clean install -Dvalidate-target-platform.failOnError=false  -Pmultiple2repo

(If you attempt to fetch sources with `-Dmirror-target-to-repo.includeSources=true` the build fails.)

**Comment by nickboldt** [comment]
If you set failOnError=true, you get:

    [INFO] Validating /home/nboldt/eclipse/workspace-jboss/jbosstools-github-master/jbosstools-locus/target-platforms/multiple/locus-multiple.target...
    [ERROR] Resolution failed:
    [ERROR]   Software being installed: org.springframework.aop 3.1.4.RELEASE
    [ERROR]   Missing requirement: org.springframework.aop 3.1.4.RELEASE requires 'package org.aopalliance.aop [1.0.0,2.0.0)' but it could not be found
    [INFO] Failed, see Error log below
    [ERROR] Validation found errors in 1 .target files:
    Could not resolve content of locus-multiple.target

**Comment by nickboldt** [comment]
Comments deleted because they no longer apply. I fixed the issue w/ missing dependencies at TP validation time. :D 

Fix: https://github.com/jbosstools/jbosstools-locus/pull/45/files#diff-f26a8a40c6eceb420a99847a51d9a1ecR25

**Comment by mickaelistria** [comment]
Seems like a good change.
Do we need the multiple2repo profile for Locus?

**Comment by pleacu** [comment]
I need this to proceed with LOCUS-42.  Since this is an independent change and needed bug fix - can we proceed with processing this PR?

**Comment by mickaelistria** [comment]
@pleacu If it's an independent change, why do you need it to be merged first?

**Comment by nickboldt** [comment]
multiple2repo is needed to make it easier to test the TP & Locus update site combo inside JBTIS.
Since there are no objections to this (I see no -1), I will merge this.

**Comment by mickaelistria** [comment]
Isn't the Locus TP meant to be purely internal? Does JBTIS consume it? What is the user story for JBTIS dev to use multiple2repo ?

**Comment by nickboldt** [comment]
User story: once upon a time, a user wanted to do local testing to verify that everything could be co-installed from Locus, Locus TP, JBTIS, JBTIS TP, etc. Let's call that user Paul. :D

**Comment by mickaelistria** [comment]
This user-story ism't valid IMO, there is actually no reason why anyone should care about the Locus TP out of Locus. It's an internal thing, it's never made available for other builds or other installations.
cc @pleacu

**Comment by pleacu** [comment]
Yes - the Locus TP is an internal thing and the build has no requirement to specify -Pmultiple2repo.  It's a profile that exists to materialize the repo locally in a convenient way in the event we want to test different local build scenarios.

**Pull request merged**
