### PR TITLE
extracted everit.xmlcommons version to property

### PR DESCRIPTION
**Pull request by adietish**
Signed-off-by: Andre Dietisheim <adietish@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
@nickboldt please review

**Comment by nickboldt** [comment]
Building https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-locus.site/ > 105

**Comment by nickboldt** [comment]
s/bunle/bundle --> Building https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-locus.site/ >= 106

**Comment by adietish** [comment]
@nickboldt awesome, that was quick. Thx!

**Pull request merged**
