### PR TITLE
JBIDE-18721: Adds new Saxon-HE version 9.5.1.6j

### PR DESCRIPTION
**Pull request by phantomjinx**
* New Teiid client in Teiid Designer requires this saxon upgrade to be in
  sync with the dependencies of the Teiid Server

* Source from 9.5.1.6j release copied in

* org.apache.xml.resolver copied in from xml-resolver 1.2 jar which is
  a dependency of the built maven jar. This satisfies class dependencies
  for the class net/sf/saxon/trans/XmlCatalogResolver

* Dependencies for this library outlined here:
  http://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.5.1-6/Saxon-HE-9.5.1-6.pom

### CODE REVIEW

**Comment by maxandersen** [comment]
1182 files ? what is so special about this to require all be checkked in when all others dont need it ?

**Comment by phantomjinx** [comment]
@maxandersen
I'm a little confused by your comment. All other components of locus have their src checked in as well! Thus, I simply followed the same template as the previous version of saxon.

As to the requirement, Teiid (as in the server project) have upgraded their dependencies on saxon-he to 9.5.1.6. This latter version is a change in API. Since Designer sources its Teiid client code from the Teiid project, the only way to address changes in API is to upgrade Designer's dependence as well.

**Comment by maxandersen** [comment]
hmm - you are right. For some reason I was convinced we fetched source from github/mvn coordinates where possible.  I guess that was in another reality ;)

**Comment by maxandersen** [comment]
I'm a bit perplexed since we have the clear goals in the readme.md:

1. Do not include jars directly into the repository, use Maven coordinates for the build as much as possible.
    * Want to keep the repository lean and clean for easy building and contributions.
1. Do not build from source, use the already available public binaries.
    * We are not trying to create forks of libraries.

So my question is still, do we really need the source here ?

**Comment by phantomjinx** [comment]
Out of date

**Pull request closed without merging**
