### PR TITLE
JBTIS-531: Provides the bouncycastle dummy plugin to share in Locus

### PR DESCRIPTION
**Pull request by phantomjinx**
* Provides a stub plugin for the satisfying of dependencies to the Apache
  Directory plugins in the JBT-IS target platform

### CODE REVIEW

**Comment by pleacu** [comment]
+1 Looks good to me - like the name change from dummy to stub

**Comment by mickaelistria** [comment]
-100 (unless I missed something). Orbit has a org.bouncycastle.bcprov bundle that contains the necessary package. There is no need to put that in Locus, just consume the bundle from our Orbit mirror in your TP.

**Comment by phantomjinx** [comment]
@mickaelistria 
So how is that bundle 'allowed' to be distributed when the entire point of Designer's stub was to avoid exporting encryption algorithms due to US ITAR restrictions, see [TEIIDDES-2667](https://issues.jboss.org/browse/TEIIDDES-2667) for the original discussion.

**Comment by mickaelistria** [comment]
I don't know about the legal, maybe @rgunber , who requested this bundle in Orbit knows more. @rgrunber : are those bouncycastle packages allowed to be distributed as part of OSS projects and Red Hat products?

**Comment by rgrunber** [comment]
The bouncycastle.bcprov has been approved by Eclipse Legal for distribution through Orbit, under the condition that certain classes be excluded.

I can't really answer the legal question but some quick searching shows that it's either approved [1] or not subject to those export controls [2].

[1]  http://www.bouncycastle.org/wiki/display/JA1/Frequently+Asked+Questions#FrequentlyAskedQuestions-11.WhatisBouncyCastle%27sexportclassificationintheUnitedStatesofAmerica
[2] https://en.wikipedia.org/wiki/Bouncy_Castle_%28cryptography%29

**Comment by pleacu** [comment]
@mickaelistria @nickboldt 
Hey guys - it sounds like this PR is okay with Mickael and suggested by Nick.  I need to spin a Luna JBTIS TP (.Final) as well as a Mars JBTIS TP so I can get the IS built for JBDSIS 8.0.4.CR3 and JBDSIS 9.0.0.Beta1.  Is a push/Locus build on one of your to-do lists (please)?
   Thkx!
ref: @phantomjinx @blafond

**Comment by mickaelistria** [comment]
Merged. Locus snapshot build is in progress. The new build should be available soon.
Will you need a release of Locus soon (to consume a stable update-site of Locus) ?

**Comment by pleacu** [comment]
yes - sorry - was working on a offline zip issue - didn;t see this update.  Please let me know when a new Locus release is available

**Comment by mickaelistria** [comment]
When do you need it?

**Comment by pleacu** [comment]
as soon as you can - QE is waiting for an updated Luna CR3 release to test and this will be in the TP

**Comment by pleacu** [comment]
this will work in both Luna and Mars correct?

**Comment by mickaelistria** [comment]
Yes, it would work for both.
The 1.4.0-SNAPSHOT of Locus contain the artifact. Please give it a try to make sure it satisfies your need, and once you have validated it, I'll release a 1.4.0 of Locus that you can use in your releases.

**Comment by pleacu** [comment]
ok - thkx!!!

**Pull request merged**
