### PR TITLE
[LOCUS-53] adding felix.log and everit.xmlcommons for rsp-server

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@nickboldt dare to review and merge, please?

**Comment by adietish** [comment]
@nickboldt dare to review and merge, please?

**Comment by nickboldt** [comment]
building here: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-locus.site/104/

**Comment by adietish** [comment]
@nickboldt thx!

**Pull request merged**
